// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5IuTC5sz31ZnIfkg3NsCoVVOhvVN3dVE',
    appId: '1:975920164791:web:73684353fd92c95fe60232',
    messagingSenderId: '975920164791',
    projectId: 'psikoz-me',
    authDomain: 'psikoz-me.firebaseapp.com',
    storageBucket: 'psikoz-me.appspot.com',
    measurementId: 'G-9E079SXTB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8X8Dd18p753vQEWkQo27g5g5m1DdTFI',
    appId: '1:975920164791:android:9c1855627c9d5b96e60232',
    messagingSenderId: '975920164791',
    projectId: 'psikoz-me',
    storageBucket: 'psikoz-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-QkKN03qDH2IyNQLvz_6FOKZS3Xjhko',
    appId: '1:975920164791:ios:e23f2ce383b64c47e60232',
    messagingSenderId: '975920164791',
    projectId: 'psikoz-me',
    storageBucket: 'psikoz-me.appspot.com',
    iosClientId: '975920164791-5qs1ikolrik3bsspgsvab44vi8bq2c2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.psikozMe',
  );
}
